### ISSUE TITLE
Decoupled TAN: "Got neither 3956 nor HITAN with tanProzess=2"

### ISSUE THREAD

**Issue by witschko** [nemiah/phpFinTS#412] opened 2023-07-25 13:13 UTC
Hey everybody,

i've been testing the decoupled TAN process with two different banks (Kreissparkasse and VR). It seems the current implementation doesn't work with both of them. Both only send `HKTAN::TAN_PROZESS_S` and DO NOT send `HKTAN::TAN_PROZESS_2` as part of a successful response (examples are attached to this issue). 

But the current implementation assumes that only messages that contain the `HKTAN::TAN_PROZESS_2` have been confirmed by the user successfully. It seems that is not correct at least for KSK and VR banks.

At the moment we solve the issue in `checkDecoupledSubmission()` by also setting `$isSuccess` to true if the HITAN is a `HKTAN::TAN_PROZESS_S` but still checking if it is an outstanding message and returning false if so.

But I'm not sure if this is the final way to go...any help is very appreciated.
[decoupled.log](https://github.com/nemiah/phpFinTS/files/12161497/decoupled.log)

**Comment by Philipp91** [comment] 2023-07-26 18:42
Okay let's see. Starting on [PDF page 37](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Security_Sicherheitsverfahren_PINTAN_2020-07-10_final_version.pdf) in section "B.4.2.2.1 Einfach-Sicherheitsfreigabe bei Prozessvariante 2", in step 2c, we today only support the "(B)" branch. However, the response that your bank sends isn't the "(A)" branch either:

1. For any 2c response, we need one HITAN with `TAN_PROZESS_2` ("Die Nachricht enthält auch ein Segment HITAN mit TANProzess=2 als Beantwortung des HKTAN.").
2. For 2c (A), we additionally need a HITAN with `TAN_PROZESS_4`.
3. For 2c (B), we additionally need a HITAN with `TAN_PROZESS_S`.

The response you posted only contains only one HITAN overall, not two. So there's the following possible explanations:

* You cropped the response / made a mistake when formatting it and there are in fact two HITAN, we just didn't see them both.
* It's not in fact a 2c response. Are you sure the authorization is done?
* The bank has a bug -- maybe they skipped over the part of the specification that I quoted in (1.) above. It's subtle at the end of a page and before the A/B list.
* It's a different scheme altogether. For instance in "B.4.2.2.2 Synchrone Eingabe von Mehrfach-Sicherheitsfreigaben in einem Dialog bei Prozessvariante 2", the final step (here it's 4c) requires only one HITAN with `TAN_PROZESS_S`. Same for B.4.2.2.3. Can you somehow confirm that we're in the simple case B.4.2.2.1 here?
* We might even be in the 2c step of those two, which is the confirmation of the _first_ authorization (that's done with one `S`), which isn't the end of the overall process. Though you received `HIRMS:4:2:3+0020::Der Auftrag wurde ausgeführt.`. Can you somehow confirm that the process is actually done at this point (and just phpFinTS doesn't realize)?

**Comment by witschko** [comment] 2023-07-27 12:33
Thank you for your quick and detailed response. I also checked B.4.2.2.1 and absolutely agree that there should be another HITAN with `TAN_PROZESS_2`.

I've attached a log of a full flow for a getStatementOfAccount which needs a TAN since the startdate is more than 3 months in the past.

So to answer you suggestions:
- It seems there is no crop or other mistake of the logs since if the Test-logger works correctly the log should be complete
- I'm sure the authorization is done because I'm getting a positive response with the statements included
- I don't think it is a bug of the bank...I have the same issues for Kreissparkasse (Baden-Württemberg) and Volksbanken/Raiffeisenbanken and both are no small banks
- I assume we are in B.4.2.2.1 but I don't know how to confirm?! I use the Secure Go Plus/S-pushTan App and just have to confirm the request in the app which seems to work

But maybe it seems i have to check with the bank...
[decoupled.log](https://github.com/nemiah/phpFinTS/files/12183469/decoupled.log)

**Comment by Philipp91** [comment] 2023-07-30 20:31
Maybe the "bug" is a widely accepted deviation from the specification, perhaps because many people missed that part in the spec or because they didn't bother to implement it that strictly (ignoring an extra segment could be the default behavior depending on how the code base is structured). Short of asking the bank, perhaps you could try the same or a similar sequence of messages/commands with a different FinTS client, and specifically client that also allows you to log the requests and responses. Then we can see whether that client receives the same response (and interprets it differently) or whether it receives a different response (due to having sent a different kind of request, in which case we'd have to look more closely on the request side).

**Comment by Masegi** [comment] 2023-09-28 10:11
Is there a way to fix this? Got this too for blz 55090500

**Comment by SegFaulty** [comment] 2023-11-11 11:24
>  Maybe the "bug" is a widely accepted deviation from the specification
run in this BUG month later on Sparkasse ...

and the solution is ... ?

**Comment by Philipp91** [comment] 2023-11-11 13:06
We need to figure out what the right way forward is. Since it seems to be a deviation from the specification, we should go with the herd, i.e. try to do what everyone else is going. And because it's not specified, we need to figure it out experimentally.

> perhaps you could try the same or a similar sequence of messages/commands with a different FinTS client, and specifically a client that also allows you to log the requests and responses. Then we can see whether that client receives the same response (and interprets it differently) or whether it receives a different response (due to having sent a different kind of request, in which case we'd have to look more closely on the request side).

**Comment by timrasche** [comment] 2024-03-12 11:32
Same on 35650000

**Comment by timrasche** [comment] 2024-03-12 12:10
Maybe this helps, the TAN segment that was returned on checkDecoupledSubmission is "S" (const TAN_PROZESS_S).

Then, line 488 there was no outstanding part found, setTanRequest is called but no action after that? 

The author wrotes "At the moment we solve the issue in checkDecoupledSubmission() by also setting $isSuccess to true if the HITAN is a HKTAN::TAN_PROZESS_S" but this doesnt help, because the origin request (where the tan was requested for) is not executed!

**Comment by Philipp91** [comment] 2024-03-14 19:45
> decoupled.log

This bank also glosses over another part of the specification: In Schritt 1a, it mandates that the response from the bank contain either `0030` or `3076`. In the latter case, we'd be done (2c immediately, which involves HIRMS to deliver the result the user wanted) -- that's clearly not what's happening. In the former case (`0030`), the bank wants additional authentication, and as per 1b it sends `HITAN(4)` and `3955`. Those two things they implemented, but the `0030` they forgot. I guess that segment is somewhat redundant, given that `3955` indicates that it's 1b just as well.

**Comment by Philipp91** [comment] 2024-03-14 19:53
> because the origin request (where the tan was requested for) is not executed!

Ah so you have the opposite experience? Because @witschko noticed this error message "as part of a successful response" and explicitly confirmed "I'm sure the authorization is done because I'm getting a positive response with the statements included".

And in your case, you say you get a response that is _not_ success (no HIRMS), but also doesn't contain 3956 (which would indicate that the authentication is still pending)?

Would you be able to post the response message you're receiving and ideally also the corresponding request that you sent? Similar to the decoupled.log files posted above -- be sure to erase sensitive details from it, without changing the length of the message, i.e. replace sensitive characters with `_` or so.

**Comment by timrasche** [comment] 2024-03-15 08:22
I'm sorry, maybe it was not clear enough. 

> And in your case, you say you get a response that is not success (no HIRMS), but also doesn't contain 3956 (which would indicate that the authentication is still pending)?

I'm pretty sure the request as @witschko wrote is success. I've forked the repo and modify the code on checkDecoupledSubmission. $isSuccess is not true because HKTAN::TAN_PROZESS_S was found in segment (i only describe the function not the underlaying data (dont know about this)). After that the code in "else" was executed. The check on $response->findRueckmeldungen(Rueckmeldungscode::STARKE_KUNDENAUTHENTIFIZIERUNG_NOCH_AUSSTEHEND) was FALSE! Therefore there is no authentication required and the setTanRequest is set. But as you can see not the processActionResponse (not part of code). On my modification i'm execute processActionResponse anyway and the result is what i need. On the origin code i got the message "there was no tan needed for this action" and its aborting if i serialize the action. With this modification it works for the moment, but i known is little bit "hacky".

I've try to extract these details from log, but needs some time (due missing sandbox and must wait for some customer to execute these steps)

**Comment by timrasche** [comment] 2024-03-15 10:37
@Philipp91 

there you go - hope it will help.

[hbci.log](https://github.com/nemiah/phpFinTS/files/14614167/hbci.log)

**Comment by Philipp91** [comment] 2024-03-16 14:12
Perfect, thanks!

Side remark: This bank also doesn't send 0030 alongside the 3955. I guess it's good that phpFinTS never insisted on this part of the spec.

It's great that your record also includes a 3956 ("not yet confirmed") response for contrast. In fact, even two of them. And then on the third status query, the confirmation is done and the server delivers the result. And as you say, it's a successful result, HIRMS is present. And as suspected, they send only HITAN(S) but not the HITAN(2) that the specification also demands. So we have to infer from the _absence_ of 3956 alone that the authentication is complete. And complete can mean successful or permanently failed, and we can infer from the presence of the result HIRMS that it was a success in this case.

Please try this patch: https://github.com/Philipp91/phpFinTS/commit/3b32a2a5881368f727fdc73c7f75019aaa496163

It should be equivalent to what you did, but less hacky.

**Comment by timrasche** [comment] 2024-03-19 09:30
Thank you very much for the patch. Quick tests on this, 1/2 banks accept this. I'll try to post another log for the bank who doesnt, asap.

**Comment by peukerjonathan** [comment] 2024-04-16 12:49
I also ran in this problem with TAN method 923 on an account from "Sparkasse Pforzheim Calw" (PZHSDE66XXX)
But there is something I noticed, maybe this helps in resolving this issue?

To force the TAN necessity I set quite a long time range when creating \Fhp\Action\GetStatementOfAccount (for example a whole year) and then do $fints->execute.
When calling $fints->execute it hits "needsTan()" and I propery receive the push message in the S-Push TAN App. I confirm the request.
Now I call $fints->checkDecoupledSubmission and get "Got neither 3956 nor HITAN with tanProzess=2"

However:
If I then do exactly the same procedure again - setting the same date range and calling $fints->execute() it actually works perfectly.

I will happily provide log files on this if you guys can quickly tell me how to gather relevant information for proper debugging? This is really not my field of expertise...

**Comment by peukerjonathan** [comment] 2024-04-18 07:46
> 
> Please try this patch: [Philipp91@3b32a2a](https://github.com/Philipp91/phpFinTS/commit/3b32a2a5881368f727fdc73c7f75019aaa496163)
> 

Just wanted to let you know - I just tested this patch and it is working fine on the Sparkasse accounts I have access to.

**Comment by timrasche** [comment] 2024-04-18 07:48
> > Please try this patch: [Philipp91@3b32a2a](https://github.com/Philipp91/phpFinTS/commit/3b32a2a5881368f727fdc73c7f75019aaa496163)
> 
> Just wanted to let you know - I just tested this patch and it is working fine on the Sparkasse accounts I have access to.

Yes can confirm that Sparkasse works. On some Volksbank accounts it doesnt, will send log soon.

**Comment by Cugar15** [comment] 2024-05-04 18:34
I am not sure whether this is part of the same issue - or just a related problem. I am happy to open a new request if advised.

I am still facing issues with Sparkasse. Since May1st, only the decoupled authentication pushTan2.0 is allowed.
I implemented a polling loop using a form and an ajax call. The patch helps - however there are some more observations:
1) $fints needs to be persisted after every on every call to $fints->checkDecoupledSubmission($action); in case of waiting status.
    Which I somewhat expected that this will be required.

2) In case of success, the instance cannot be persisted since the following exception is thrown:

```
Fatal error:  Uncaught RuntimeException: Cannot serialize this action, because it is not waiting for a TAN. 
in C:\xampp\htdocs\vendor\nemiah\php-fints\lib\Fhp\BaseAction.php:89

Stack trace:

#0 C:\xampp\htdocs\vendor\nemiah\php-fints\lib\Fhp\PaginateableAction.php(48): Fhp\BaseAction-&gt;__serialize()
#1 C:\xampp\htdocs\vendor\nemiah\php-fints\lib\Fhp\Action\GetStatementOfAccount.php(95): Fhp\PaginateableAction-&gt;__serialize()
#2 [internal function]: Fhp\Action\GetStatementOfAccount-&gt;__serialize()
#3 C:\xampp\htdocs\administrator\includes\adm_konto_check.php(242): serialize(Object(Fhp\Action\GetStatementOfAccount))
#4 C:\xampp\htdocs\administrator\includes\adm_konto_check.php(1045): storeFinTs(Object(Fhp\Action\GetStatementOfAccount))
#5 {main}
  thrown in <b>C:\xampp\htdocs\vendor\nemiah\php-fints\lib\Fhp\BaseAction.php</b> on line <b>89</b><br />

```
3) Observation: Once the authentication is completed, the bank sends the StatementOfAccount right away - which can be seen in the logger.
    There is no further call needed - and I did not expect this to happen.

4) Since the check for authentication happens in the polling routine, the send data is ignored and the code returns to the main routine and tries to retrieve the StatementOfAccount - pretty much the same way like in the example. 
The persisted $fints is recreated (which is the last one in waiting state!), and now the following exception is thrown:


```
Fatal error: Uncaught Fhp\Protocol\TanRequiredException: This action requires a TAN to be completed. 
in C:\xampp\htdocs\vendor\nemiah\php-fints\lib\Fhp\BaseAction.php:165 

Stack trace: 
#0 C:\xampp\htdocs\vendor\nemiah\php-fints\lib\Fhp\Action\GetStatementOfAccount.php(146): Fhp\BaseAction->ensureDone() 
#1 C:\xampp\htdocs\administrator\includes\adm_konto_check.php(742): Fhp\Action\GetStatementOfAccount->getStatement() 
#2 {main} thrown in C:\xampp\htdocs\vendor\nemiah\php-fints\lib\Fhp\BaseAction.php on line 165
```

A further logon attempt will not require an authentication anymore and the SoA can be retrieved.
This tells me, that after logon, the new created $fints captures the desired status.

Here is the question: 

I tend to believe that the $fints needs to be persisted after success to capture the information that there is no TAN required anymore.
However, this seems to be blocked.
What am I missing here?

**Closed** 2024-07-13 04:11 UTC
